[profile.default]

src = 'src'
test = 'test'
libs = ['lib']

out = '../build/periphery'
cache_path = '../cache/periphery'

via_ir = true
optimizer = true
optimizer_runs = 1000000
gas_reports = []

auto_detect_remappings = true
remappings = [
    'forge-std/=lib/core/lib/forge-std/src',

    'solmate/=lib/core/lib/solmate/src/',

    'foundry-verification-bug-core/=lib/core/src/'
]

allow_paths = [
    '../core'
]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
